name: WINKLER_PRC_paper
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.10.1
  - nbformat
  - nbconvert
  - ipykernel
  - numpy=2.2.4
  - scipy=1.15.2
  - pip
  - pip:
      - git+https://github.com/bendichter/brokenaxes.git
